apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen-rhdh-test-app-2
  janus-idp.io/tekton: codegen-rhdh-test-app-2
  backstage.io/kubernetes-id: codegen-rhdh-test-app-2
  backstage.io/kubernetes-namespace: rhdh-apps 
  app.kubernetes.io/part-of: codegen-rhdh-test-app-2
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml